.rubocop.yml, .travis.yml, README.md, junk_drawer.gemspec, lib/junk_drawer/rails.rb, lib/junk_drawer/rails/bulk_updatable.rb, spec/junk_drawer/rails/bulk_updatable_spec.rb, spec/spec_helper.rb
This introduces a `BulkUpdatable` module which can be included in
`ActiveRecord` models. I added a nested `rails/` directory which can be
optionally required. If a user wants only the plain ruby stuff, they can
`require 'junk_drawer'`. If they want both they can `require
'junk_drawer/rails'`.
=> Introduce BulkUpdatable

bin/setup
When setting up the dev environment, running `rake test` requires a
`postgres` user and `junk_drawer_test` database, so this adds them.
=> Create user and test database in bin/setup

.gitignore, .travis.yml, Gemfile, README.md, bin/test, gemfiles/rails_4.2.gems, gemfiles/rails_5.0.gems, junk_drawer.gemspec, lib/junk_drawer/rails/bulk_updatable.rb
`JunkDrawer::BulkUpdatable` uses the `ActiveRecord::ConnectionAdapters`
`::PostgreSQL::OID::Hstore` and `::Jsonb` `#type_cast_for_database`
method, which was renamed to `serialize` in ActiveRecord 5. This adds
logic to use the appropriate method based on ActiveRecord version.
It also creates separate gem files for each supported ActiveRecord
version for testing.
=> Update method usage to support ActiveRecord 5

lib/junk_drawer/callable.rb, spec/junk_drawer/callable_spec.rb
This fixes an issue where using the class level `call` method cannot
be used with a block.
=> Bugs: pass block down to Callable instance method

spec/junk_drawer/rails/bulk_updatable_spec.rb, spec/spec_helper.rb
I'm planning on adding a bunch more types to the tests, so wanted to
make it easier to add them without needing to come up with witty names
for each.
A side effect of this change is that I discovered that `hstore` wasn't
being tested because it was getting overridden by the `jsonb` column
with the same name. I added a line to `spec_helper.rb` to create the
`hstore` extension if it doesn't already exist, being that it didn't
exist for me in the test database at first.
=> BulkUpdatable: refactor test to loop through types

.rubocop.yml, spec/junk_drawer/rails/bulk_updatable_spec.rb, spec/spec_helper.rb, spec/support/shared_examples/bulk_updatable_type.rb
I'm going to be adding a lot more types to be tested against here, so
wanted to make them a little more generic. This adds a new set of shared
examples and runs them against each type. I added a `GENERATORS` hash to
generate data for each type and a couple of helper methods in the test.
One weird thing is that in order to access `type` in the methods, I
needed to set it in a `let`, otherwise it would throw a `NoMethodError`.
=> BulkUpdatable: extract specs to shared examples

lib/junk_drawer/rails/bulk_updatable.rb, spec/junk_drawer/rails/bulk_updatable_spec.rb, spec/support/shared_examples/bulk_updatable_type.rb
This is probably all of the major simple types we might want to cover
for now, however we still need to handle array type columns, such as
integer or string arrays. This will come in a followup.
**Notes**
- I tried to implement `bigint` and `time` types, but it looks like
those may be a little more complicated. Probably fine for now, but
Rails now defaults primary key columns to `bigint`. This will only
become a problem when we hit a primary key that is greater than
2,147,483,647, so we've got time to handle that.
- Likewise, there are a whole bunch of other column types we might at
some point want to support, but this seemed like it covered the vast
majority of use cases.
https://www.postgresql.org/docs/10/static/datatype-numeric.html …
=> BulkUpdatable: add support for a host of new types

lib/junk_drawer/rails/bulk_updatable.rb
While `string` and `text` are basically the default Postgres assumes, I
think it'll be better to have this be explicit, especially since all
other types are in the map. This will also help accommodate array type
columns, since we need to cast using `::string[]` or `::int[]` for
those.
=> BulkUpdatable: switch to using fetch for cast

lib/junk_drawer/rails/bulk_updatable.rb
`ActiveRecord` has a method `type_for_attribute` which returns some sort
of `Value` object which already knows how to serialize the particular
value. No need for us to map it ourselves. I learned about this by
poring over the source code for the `activerecord-import` gem.
https://github.com/zdennis/activerecord-import/blob/master/lib/activerecord-import/import.rb#L866
http://api.rubyonrails.org/classes/ActiveRecord/ModelSchema/ClassMethods.html#method-i-type_for_attribute
=> BulkUpdatable: use AR to get type cast

lib/junk_drawer/rails/bulk_updatable.rb
It's nice to have it multi-line for code readability, but squishing it
all down to one line will be a little more log friendly, and also
consistent with the rest of the really long queries that get generated
in Rails, which are always one line.
=> BulkUpdatable: `squish` SQL query

junk_drawer.gemspec
`pry-byebug` adds debugger commands to `pry` so we can use things like
`next`, `skip`, `continue`, etc.
https://github.com/deivid-rodriguez/pry-byebug
This is not included by default, so in order to use this during
development, we need to add `require 'pry-byebug'` to the top of files.
=> Tools: add `pry-byebug`

lib/junk_drawer/rails/bulk_updatable.rb, spec/junk_drawer/rails/bulk_updatable_spec.rb, spec/support/shared_examples/bulk_updatable_type.rb
So it turns out we can apparently use `column.sql_type` for the cast.
How cool is that? I also added a few more types to the tests, and a list
of other types we might want to test at some point. Not sure how
important it is, though, to test all of them, being that it seems like
the generalized `sql_type` might just cover our butts on all types.
=> BulkUpdatable: remove manual type cast map

Gemfile, gemfiles/rails_4.2.gems, gemfiles/rails_5.0.gems, spec/junk_drawer/rails/bulk_updatable_spec.rb, spec/support/shared_examples/bulk_updatable_type.rb
Turns out `hstore_accessor` works out of the box, but this adds tests to
verify it. No such luck with `jsonb_accessor`, so support for that will
be forthcoming.
I had to make a couple of adjustments to the tests:
- Changed `pluck` to `map`. Since `hstore_accessor` values are nested,
they don't correspond to a database column which can be `pluck`ed.
- Adding the `&` in front of `getter_name` means it needs to be a
symbol, since the `to_proc` operator doesn't work on strings.
- Added `value` to be returned from the generated values. I think this
is maybe a little more clear anyway, but this was actually really
interesting behavior. One thing about ruby is that when you call a
setter it *always* returns the thing that was passed in, regardless of
return value. Except if you use `send`: …
=> BulkUpdatable: add tests for `hstore_accessor`

lib/junk_drawer/rails/bulk_updatable.rb, spec/junk_drawer/rails/bulk_updatable_spec.rb
Pretty simple. When we call `#save` on a record, ActiveRecord clears
changes, so it makes sense to do the same when bulk updating. One thing
of note is that `clear_changes_information` clobbers all change
information. `#save` moves `changes` to `previous_changes`, which ought
to be possible via the `#changes_applied` method, but there appears to
be some weird caching going on preventing this from working, so we went
with `#clear_changes_information`, which clears both `changes` and
`previous_changes`. This may be something we can revisit in Rails 5.2 or
later, as it appears this logic has shifted quite a bit.
Rails 5.1:
https://github.com/rails/rails/blob/v5.1.6/activerecord/lib/active_record/attribute_methods/dirty.rb#L71-L83
Rails 5.2, no change tracking methods: …
=> BulkUpdatable: clear changes after query

.travis.yml, junk_drawer.gemspec, lib/junk_drawer/callable.rb, spec/junk_drawer/notifier/honeybadger_strategy_spec.rb
Ruby complains about implicitly passing a hash as keyword arguments. If
we want to pass in a hash that will be slurped up on the other side with
`**`, then we need to splat it out with `**` when we're calling it. This
fixes deprecation warnings to this effect, though the fixes should be
backwards compatible.
**Notes**
* I removed the `bundler` version from the `gemspec` file. I don't think
it makes any sense to have in there.
* I added more ruby versions to the `.travis.yml` section. We can
probably deprecate some of the older versions we're testing against.
=> Upgrades: fix deprecations in Ruby 2.7

lib/junk_drawer/version.rb
This will release the update to fix deprecation warnings for Ruby 2.7.
=> bump version

junk_drawer.gemspec, lib/junk_drawer/callable.rb, spec/junk_drawer/callable_spec.rb
Fixes #28. Ruby 2.6 splat arguments behave differently from Ruby 2.7
splat arguments which behave (slightly) differently from Ruby 3.0 splat
arguments. It turns out it's hard to handle all of them gracefully, but
thankfully a little gem called [`ruby2_keywords`][rbkw] is provided by
Ruby core for us to transition smoothly. For Ruby versions 2.6 and
earlier, it is a no-op. For Ruby versions 2.7 and up, the method is
already defined in core Ruby, in which cases the gem does nothing. The
core version internally translates the arguments to Ruby 3 style keyword
arguments. You can read all about the complexities [here][blog]. There
are several other suggested ways of handling the issue, but this seemed
to be the cleanest. Once Ruby <= 2.6 support is dropped, this should be
able to be removed. …
=> Upgrades: fix keyword arguments across versions

.gitignore, README.md, lib/junk_drawer/notifier.rb, spec/junk_drawer/notifier_spec.rb
**What**
Updates JunkDrawer::Notifier to accept any arbitrary class as a
strategy, as long as the class implements a call method.
**Why**
Currently, there are only a few pre-defined strategies that the Notifier
can be configured with. This addition provides a lot more flexibility,
allowing users of the gem to define their own custom strategies on the
fly.
[ch14664](https://app.clubhouse.io/informedk12/story/14664/update-junkdrawer-notifier-to-accept-a-callable-strategy)
=> Notifier: add ability to configure with arbitrary callable strategy

Gemfile
**What**
Upgrades Active Record and Active Support to version 5.2.x
**Why**
There are unpatched vulnerablities on the version we were using and they
are fixed in 5.2.4.5.
=> Bump Active Record & Active Support to 5.2.x

lib/junk_drawer/rails/bulk_updatable.rb, lib/junk_drawer/version.rb, spec/junk_drawer/rails/bulk_updatable_spec.rb
**What**
This updates `BulkUpdatable` to use `changes_applied` rather than
`clear_changes_information`.
**Why**
`changes_applied` is what `ActiveRecord` uses internally when a model is
saved. It takes the current changes and tracks them as previous changes
so that you can see what changed even after a model has been saved.
Libraries like `CarrierWave` rely on this to figure out which records
need to have corresponding files removed/updated after a save. On the
other hand, `clear_changes_information` clears *all* information about
changes, which makes it impossible to figure out what changed.
=> Rails: use changes_applied on bulk update

Gemfile, gemfiles/rails_5.0.gems, spec/junk_drawer/rails/bulk_updatable_spec.rb
It hasn't been maintained in several years. We can hold onto
`jsonb_accessor` for now as it is being maintained.
=> Upgrades: remove hstore_accessor

.github/workflows/ruby.yml
**Why**
This should allow us to upgrade Rubocop, which should then allow us to
add newer Ruby versions.
=> Upgrades: remove Ruby versions 2.4, 2.5 from build 

.github/workflows/ruby.yml, Gemfile, gemfiles/rails_5.0.gems, gemfiles/rails_7.0.gems, junk_drawer.gemspec
Leaving off Ruby 3.2 for the moment as it will likely break.
**Notes**
I removed the `pg` gem from the `gemspec` file, as that version is not
compatible with Ruby 3. I moved it to `rails_7.0.gems` so it can be
managed alongside the Rails dependencies.
=> Upgrades: update tested Rails/Ruby versions

.github/workflows/ruby.yml, junk_drawer.gemspec, lib/junk_drawer/callable.rb, lib/junk_drawer/notifier.rb, spec/junk_drawer/notifier_spec.rb
This fixes a couple of issues around keyword arguments. When there is a
keyword argument passed it would raise an error:
```
ArgumentError: wrong number of arguments (given 2, expected 1)
```
=> Upgrades: add Ruby 3.2 support 

lib/junk_drawer/rails/bulk_updatable.rb, lib/junk_drawer/version.rb
The last change inadvertantly started setting `id = temp_table.id`.
Previously this was not the case and it is unecessary to do.
**Before:**
without prepared statements
```
UPDATE with_model_bulk_updatable_models_33097_4240 SET "id" = tmp_table."id", "string_value" = tmp_table."string_value", "updated_at" = tmp_table."updated_at" FROM (VALUES (1, 'thing_0'::character varying, '2023-05-19 00:22:02.382888'::timestamp(6) without time zone), (2, 'thing_1'::character varying, '2023-05-19 00:22:02.382888'::timestamp(6) without time zone)) AS tmp_table(id, string_value, updated_at) WHERE with_model_bulk_updatable_models_33097_4240.id = tmp_table.id
```
with prepared statements
```
UPDATE with_model_bulk_updatable_models_33097_4240 SET "id" = tmp_table."id", "string_value" = …
```
=> BulkUpdatable: Do not unecessarily update id
